<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-16 at 08:18:07.
 */
class GenericTagTest extends PHPUnit_Framework_TestCase {

    /**
     * @var GenericTag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GenericTag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
